version: '2.27.1'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_pollution
    environment:
      MYSQL_ROOT_PASSWORD: Jc
      MYSQL_DATABASE: db_geolocalitation
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql